-- =====================================================================
-- TurismoUQ-App - 01_tablas_auth.sql
-- Tablas SOLO para la app (login de clientes + panel admin). Viven en
-- el mismo esquema turismouq pero por fuera de las 14 tablas del
-- entregable academico - no modifican CLIENTE ni ninguna tabla
-- calificada de la Entrega 1.
-- Ejecutar conectado como: turismouq/<tu_clave>@//localhost:1521/XEPDB1
-- =====================================================================

CREATE TABLE app_credencial_cliente (
  id_cliente      NUMBER PRIMARY KEY REFERENCES cliente (id_cliente),
  password_hash   VARCHAR2(200) NOT NULL,
  fecha_creacion  DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE app_usuario_admin (
  id_admin        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  username        VARCHAR2(50) NOT NULL,
  password_hash   VARCHAR2(200) NOT NULL,
  nombre          VARCHAR2(100) NOT NULL,
  activo          CHAR(1) DEFAULT 'S' NOT NULL CHECK (activo IN ('S', 'N')),
  fecha_creacion  DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT uq_app_usuario_admin_username UNIQUE (username)
);

COMMIT;
